
export const currencies = [
    { value: "USD", label: "USD - United States Dollar" },
    { value: "EUR", label: "EUR - Euro" },
    { value: "JPY", label: "JPY - Japanese Yen" },
    { value: "GBP", label: "GBP - British Pound Sterling" },
    { value: "AUD", label: "AUD - Australian Dollar" },
    { value: "CAD", label: "CAD - Canadian Dollar" },
    { value: "CHF", label: "CHF - Swiss Franc" },
    { value: "CNY", label: "CNY - Chinese Yuan" },
    { value: "INR", label: "INR - Indian Rupee" },
    { value: "AED", label: "AED - United Arab Emirates Dirham" },
    { value: "AFN", label: "AFN - Afghan Afghani" },
    { value: "ALL", label: "ALL - Albanian Lek" },
    { value: "AMD", label: "AMD - Armenian Dram" },
    { value: "ANG", label: "ANG - Netherlands Antillean Guilder" },
    { value: "AOA", label: "AOA - Angolan Kwanza" },
    { value: "ARS", label: "ARS - Argentine Peso" },
    { value: "AWG", label: "AWG - Aruban Florin" },
    { value: "AZN", label: "AZN - Azerbaijani Manat" },
    { value: "BAM", label: "BAM - Bosnia-Herzegovina Convertible Mark" },
    { value: "BBD", label: "BBD - Barbadian Dollar" },
    { value: "BDT", label: "BDT - Bangladeshi Taka" },
    { value: "BGN", label: "BGN - Bulgarian Lev" },
    { value: "BHD", label: "BHD - Bahraini Dinar" },
    { value: "BIF", label: "BIF - Burundian Franc" },
    { value: "BMD", label: "BMD - Bermudan Dollar" },
    { value: "BND", label: "BND - Brunei Dollar" },
    { value: "BOB", label: "BOB - Bolivian Boliviano" },
    { value: "BRL", label: "BRL - Brazilian Real" },
    { value: "BSD", label: "BSD - Bahamian Dollar" },
    { value: "BTN", label: "BTN - Bhutanese Ngultrum" },
    { value: "BWP", label: "BWP - Botswanan Pula" },
    { value: "BYR", label: "BYR - Belarusian Ruble" },
    { value: "BZD", label: "BZD - Belize Dollar" },
    { value: "CDF", label: "CDF - Congolese Franc" },
    { value: "CLP", label: "CLP - Chilean Peso" },
    { value: "COP", label: "COP - Colombian Peso" },
    { value: "CRC", label: "CRC - Costa Rican Colón" },
    { value: "CUC", label: "CUC - Cuban Convertible Peso" },
    { value: "CUP", label: "CUP - Cuban Peso" },
    { value: "CVE", label: "CVE - Cape Verdean Escudo" },
    { value: "CZK", label: "CZK - Czech Republic Koruna" },
    { value: "DJF", label: "DJF - Djiboutian Franc" },
    { value: "DKK", label: "DKK - Danish Krone" },
    { value: "DOP", label: "DOP - Dominican Peso" },
    { value: "DZD", label: "DZD - Algerian Dinar" },
    { value: "EGP", label: "EGP - Egyptian Pound" },
    { value: "ERN", label: "ERN - Eritrean Nakfa" },
    { value: "ETB", label: "ETB - Ethiopian Birr" },
    { value: "FJD", label: "FJD - Fijian Dollar" },
    { value: "FKP", label: "FKP - Falkland Islands Pound" },
    { value: "GEL", label: "GEL - Georgian Lari" },
    { value: "GHS", label: "GHS - Ghanaian Cedi" },
    { value: "GIP", label: "GIP - Gibraltar Pound" },
    { value: "GMD", label: "GMD - Gambian Dalasi" },
    { value: "GNF", label: "GNF - Guinean Franc" },
    { value: "GTQ", label: "GTQ - Guatemalan Quetzal" },
    { value: "GYD", label: "GYD - Guyanaese Dollar" },
    { value: "HKD", label: "HKD - Hong Kong Dollar" },
    { value: "HNL", label: "HNL - Honduran Lempira" },
    { value: "HRK", label: "HRK - Croatian Kuna" },
    { value: "HTG", label: "HTG - Haitian Gourde" },
    { value: "HUF", label: "HUF - Hungarian Forint" },
    { value: "IDR", label: "IDR - Indonesian Rupiah" },
    { value: "ILS", label: "ILS - Israeli New Sheqel" },
    { value: "IQD", label: "IQD - Iraqi Dinar" },
    { value: "IRR", label: "IRR - Iranian Rial" },
    { value: "ISK", label: "ISK - Icelandic Króna" },
    { value: "JMD", label: "JMD - Jamaican Dollar" },
    { value: "JOD", label: "JOD - Jordanian Dinar" },
    { value: "KES", label: "KES - Kenyan Shilling" },
    { value: "KGS", label: "KGS - Kyrgystani Som" },
    { value: "KHR", label: "KHR - Cambodian Riel" },
    { value: "KMF", label: "KMF - Comorian Franc" },
    { value: "KPW", label: "KPW - North Korean Won" },
    { value: "KRW", label: "KRW - South Korean Won" },
    { value: "KWD", label: "KWD - Kuwaiti Dinar" },
    { value: "KYD", label: "KYD - Cayman Islands Dollar" },
    { value: "KZT", label: "KZT - Kazakhstani Tenge" },
    { value: "LAK", label: "LAK - Laotian Kip" },
    { value: "LBP", label: "LBP - Lebanese Pound" },
    { value: "LKR", label: "LKR - Sri Lankan Rupee" },
    { value: "LRD", label: "LRD - Liberian Dollar" },
    { value: "LSL", label: "LSL - Lesotho Loti" },
    { value: "LYD", label: "LYD - Libyan Dinar" },
    { value: "MAD", label: "MAD - Moroccan Dirham" },
    { value: "MDL", label: "MDL - Moldovan Leu" },
    { value: "MGA", label: "MGA - Malagasy Ariary" },
    { value: "MKD", label: "MKD - Macedonian Denar" },
    { value: "MMK", label: "MMK - Myanma Kyat" },
    { value: "MNT", label: "MNT - Mongolian Tugrik" },
    { value: "MOP", label: "MOP - Macanese Pataca" },
    { value: "MRO", label: "MRO - Mauritanian Ouguiya" },
    { value: "MUR", label: "MUR - Mauritian Rupee" },
    { value: "MVR", label: "MVR - Maldivian Rufiyaa" },
    { value: "MWK", label: "MWK - Malawian Kwacha" },
    { value: "MXN", label: "MXN - Mexican Peso" },
    { value: "MYR", label: "MYR - Malaysian Ringgit" },
    { value: "MZN", label: "MZN - Mozambican Metical" },
    { value: "NAD", label: "NAD - Namibian Dollar" },
    { value: "NGN", label: "NGN - Nigerian Naira" },
    { value: "NIO", label: "NIO - Nicaraguan Córdoba" },
    { value: "NOK", label: "NOK - Norwegian Krone" },
    { value: "NPR", label: "NPR - Nepalese Rupee" },
    { value: "NZD", label: "NZD - New Zealand Dollar" },
    { value: "OMR", label: "OMR - Omani Rial" },
    { value: "PEN", label: "PEN - Peruvian Nuevo Sol" },
    { value: "PGK", label: "PGK - Papua New Guinean Kina" },
    { value: "PHP", label: "PHP - Philippine Peso" },
    { value: "PKR", label: "PKR - Pakistani Rupee" },
    { value: "PLN", label: "PLN - Polish Zloty" },
    { value: "PYG", label: "PYG - Paraguayan Guarani" },
    { value: "QAR", label: "QAR - Qatari Rial" },
    { value: "RON", label: "RON - Romanian Leu" },
    { value: "RSD", label: "RSD - Serbian Dinar" },
    { value: "RUB", label: "RUB - Russian Ruble" },
    { value: "RWF", label: "RWF - Rwandan Franc" },
    { value: "SAR", label: "SAR - Saudi Riyal" },
    { value: "SBD", label: "SBD - Solomon Islands Dollar" },
    { value: "SCR", label: "SCR - Seychellois Rupee" },
    { value: "SDG", label: "SDG - Sudanese Pound" },
    { value: "SEK", label: "SEK - Swedish Krona" },
    { value: "SGD", label: "SGD - Singapore Dollar" },
    { value: "SHP", label: "SHP - Saint Helena Pound" },
    { value: "SLL", label: "SLL - Sierra Leonean Leone" },
    { value: "SOS", label: "SOS - Somali Shilling" },
    { value: "SRD", label: "SRD - Surinamese Dollar" },
    { value: "SSP", label: "SSP - South Sudanese Pound" },
    { value: "STD", label: "STD - São Tomé and Príncipe Dobra" },
    { value: "SVC", label: "SVC - Salvadoran Colón" },
    { value: "SYP", label: "SYP - Syrian Pound" },
    { value: "SZL", label: "SZL - Swazi Lilangeni" },
    { value: "THB", label: "THB - Thai Baht" },
    { value: "TJS", label: "TJS - Tajikistani Somoni" },
    { value: "TMT", label: "TMT - Turkmenistani Manat" },
    { value: "TND", label: "TND - Tunisian Dinar" },
    { value: "TOP", label: "TOP - Tongan Paʻanga" },
    { value: "TRY", label: "TRY - Turkish Lira" },
    { value: "TTD", label: "TTD - Trinidad and Tobago Dollar" },
    { value: "TWD", label: "TWD - New Taiwan Dollar" },
    { value: "TZS", label: "TZS - Tanzanian Shilling" },
    { value: "UAH", label: "UAH - Ukrainian Hryvnia" },
    { value: "UGX", label: "UGX - Ugandan Shilling" },
    { value: "UYU", label: "UYU - Uruguayan Peso" },
    { value: "UZS", label: "UZS - Uzbekistan Som" },
    { value: "VND", label: "VND - Vietnamese Dong" },
    { value: "VUV", label: "VUV - Vanuatu Vatu" },
    { value: "WST", label: "WST - Samoan Tala" },
    { value: "XAF", label: "XAF - CFA Franc BEAC" },
    { value: "XCD", label: "XCD - East Caribbean Dollar" },
    { value: "XDR", label: "XDR - Special Drawing Rights" },
    { value: "XOF", label: "XOF - CFA Franc BCEAO" },
    { value: "XPF", label: "XPF - CFP Franc" },
    { value: "YER", label: "YER - Yemeni Rial" },
    { value: "ZAR", label: "ZAR - South African Rand" },
    { value: "ZMW", label: "ZMW - Zambian Kwacha" },
    { value: "ZWL", label: "ZWL - Zimbabwean Dollar" },
].sort((a, b) => a.label.localeCompare(b.label));

export const currencyCodes = currencies.map(c => c.value) as [string, ...string[]];

export const countries = [
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'Andorra', label: 'Andorra' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Belarus', label: 'Belarus' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Benin', label: 'Benin' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'Brunei', label: 'Brunei' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Burkina Faso', label: 'Burkina Faso' },
  { value: 'Burundi', label: 'Burundi' },
  { value: 'Cabo Verde', label: 'Cabo Verde' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Central African Republic', label: 'Central African Republic' },
  { value: 'Chad', label: 'Chad' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Comoros', label: 'Comoros' },
  { value: 'Congo, Democratic Republic of the', label: 'Congo, Democratic Republic of the' },
  { value: 'Congo, Republic of the', label: 'Congo, Republic of the' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Cote d\'Ivoire', label: 'Cote d\'Ivoire' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Cyprus', label: 'Cyprus' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Dominican Republic', label: 'Dominican Republic' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
  { value: 'Eritrea', label: 'Eritrea' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Eswatini', label: 'Eswatini' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'Gabon', label: 'Gabon' },
  { value: 'Gambia', label: 'Gambia' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Grenada', label: 'Grenada' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guinea', label: 'Guinea' },
  { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Haiti', label: 'Haiti' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Iran', label: 'Iran' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kiribati', label: 'Kiribati' },
  { value: 'Kosovo', label: 'Kosovo' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'Laos', label: 'Laos' },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Lesotho', label: 'Lesotho' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'Libya', label: 'Libya' },
  { value: 'Liechtenstein', label: 'Liechtenstein' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Madagascar', label: 'Madagascar' },
  { value: 'Malawi', label: 'Malawi' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mali', label: 'Mali' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Marshall Islands', label: 'Marshall Islands' },
  { value: 'Mauritania', label: 'Mauritania' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Micronesia', label: 'Micronesia' },
  { value: 'Moldova', label: 'Moldova' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Mozambique', label: 'Mozambique' },
  { value: 'Myanmar (Burma)', label: 'Myanmar (Burma)' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'North Korea', label: 'North Korea' },
  { value: 'North Macedonia', label: 'North Macedonia' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Palestine', label: 'Palestine' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Russia', label: 'Russia' },
  { value: 'Rwanda', label: 'Rwanda' },
  { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
  { value: 'Saint Lucia', label: 'Saint Lucia' },
  { value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'San Marino', label: 'San Marino' },
  { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Sierra Leone', label: 'Sierra Leone' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'Solomon Islands', label: 'Solomon Islands' },
  { value: 'Somalia', label: 'Somalia' },
  { value: 'South Africa', label: 'South Africa' },
  { value: 'South Korea', label: 'South Korea' },
  { value: 'South Sudan', label: 'South Sudan' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Sudan', label: 'Sudan' },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Syria', label: 'Syria' },
  { value: 'Taiwan', label: 'Taiwan' },
  { value: 'Tajikistan', label: 'Tajikistan' },
  { value: 'Tanzania', label: 'Tanzania' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Timor-Leste', label: 'Timor-Leste' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Turkmenistan', label: 'Turkmenistan' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'United Arab Emirates', label: 'United Arab Emirates' },
  { value: 'United Kingdom', label: 'United Kingdom' },
  { value: 'United States', label: 'United States' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Uzbekistan', label: 'Uzbekistan' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Vatican City', label: 'Vatican City' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Vietnam', label: 'Vietnam' },
  { value: 'Yemen', label: 'Yemen' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
].sort((a, b) => a.label.localeCompare(b.label));

export const countryCodes = countries.map(c => c.value) as [string, ...string[]];
